spring:
  application:
    name: my-bot
  datasource:
    url: jdbc:postgresql://localhost:5432/telegram-bot
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
telegram:
  bot:
    token: "7727322139:AAGdHVMa4YfNJ-ekUIAmCIFCgaMZcAIGa00"
    username: "nikkitavr_personal_assistant_bot"